[package]
name = "parseentities"
version = "0.0.0"
edition = "2021"

[dependencies]
prost = "0.11"
snap = "1.1"
muerta = { path = "../../muerta" }

[features]
bumpalo = ["dep:bumpalo"]

[dependencies.bumpalo]
version = "3.9"
features = ["allocator_api"]
optional = true
