[package]
name = "muerta"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.3.0"
prost = "0.11.3"
anyhow = "1.0.66"
byteorder = "1.4.3"
snap = "1.1.0"
thiserror = "1.0.38"
derivative = "2.2.0"

[build-dependencies]
prost-build = "0.11.4"
