[package]
name = "muerta"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.11.3"
snap = "1.1.0"
thiserror = "1.0.38"
compact_str = { version = "0.6.1", features = [] }
hashbrown = { version = "0.13.2", features = ["ahash", "inline-more", "nightly"] }

[dev-dependencies]
expect-test = "1.4.0"

[build-dependencies]
prost-build = "0.11.4"
