[package]
name = "muerta"
version = "0.0.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
prost = "0.11"
snap = "1.1"
hashbrown = { version = "0.13", features = ["ahash", "inline-more", "nightly"] }
dyn-clone = "1.0.12"

[build-dependencies]
prost-build = "0.11"
