[package]
# TODO: rename to deflat, because we're not flattening stuff, but deflattening
name = "haste_dota2_deflat"
version = "0.0.0"
edition = "2021"

[dependencies]
haste_dota2_deflat_atoms = { path = "../../crates/haste_dota2_deflat_atoms" }
