[package]
name = "uniquetypes"
version = "0.0.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
haste = { workspace = true, features = ["preserve-metadata"] }
haste_vartype.workspace = true
