[package]
name = "haste_vartype"
version = "0.0.0"
edition.workspace = true

[dependencies]
dungers = { workspace = true, features = ["charsor"] }
thiserror.workspace = true

[dev-dependencies]
expect-test.workspace = true
